// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvwqllaixdatjcyogncx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2d3FsbGFpeGRhdGpjeW9nbmN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MTU4NTYsImV4cCI6MjA2MDI5MTg1Nn0.krMWn1IrvpM62MKaDNhTzUZFWJ3Gh5PwZYECO2oaqRo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);